version: "3.7"

services: 
  php-fpm:
    ports:
      - "8075:80"
    build:
      context: .
      target: php-base
      dockerfile: Dockerfile
    container_name: latam_app
    volumes:
        - ./src:/var/www/html
  db:
    container_name: latam_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '33075:3306'